### ISSUE TITLE
Need to declare Get Controllers in every Widget manually everytime.

### ISSUE THREAD

**Issue by hrithikrtiwari** [jonataslaw/get_cli#114]
░██████╗░███████╗████████╗   ░█████╗░██╗░░░░░░██╗
██╔════╝░██╔════╝╚══██╔══╝   ██╔══██╗██║░░░░░░██║
██║░░██╗░█████╗░░░░░██║░░░   ██║░░╚═╝██║░░░░░░██║
██║░░╚██╗██╔══╝░░░░░██║░░░   ██║░░██╗██║░░░░░░██║
╚██████╔╝███████╗░░░██║░░░   ╚█████╔╝███████╗ ██║
░╚═════╝░╚══════╝░░░╚═╝░░░   ░╚════╝░╚══════╝ ╚═╝

Version: 1.6.0

# Issue facing
I am able to successfully run the app but:
- I have to declare the default controller everytime [on every stateful widget] to initialize the controller, spent my whole day figuring it out
- It shows no error to me upon not declaring a controller and directly using it in my buttons.. rather gives a runtime error
- I also have to Get.put the controllers in the child Widgets (stateful for reusability) which I have declared in the same file

My issue could have a possible relation with #19
## this works 
```
class WelcomeView extends GetView<WelcomeController> {
  final WelcomeController controller = Get.put(WelcomeController());
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(),
    );
  }
}
```
## Unfortunately this doesn't
```
class WelcomeView extends GetView<WelcomeController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(),
    );
  }
}
```

pubspec.yaml
-------------------------------------------------------------------------------------------------------------------

```
name: contrack
version: 1.0.0+1
publish_to: none
description: Track your Materials Delivered on Construction Sites.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_auth: 3.0.1
  google_sign_in: 5.0.7
  firebase_core: 1.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

```
## Everytime I hot reload, I see this.. and upon hot restart error is gone.. 
![image](https://user-images.githubusercontent.com/42163313/129393941-6a720184-2a44-4254-8375-a6d1739a5def.png)

Note; used `HomeBinding().dependencies()` in the main.dart in the main() 

Also this application was absolutely generated using Get_cli using GetXPattern
