### ISSUE TITLE
`getx sort` does not apply the rules configured in the `analysis_options.yaml`.

### ISSUE THREAD

**Issue by wtto00** [jonataslaw/get_cli#214]
File analysis_options.yaml:
```yaml
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    line_length:
      # specify the maximum line length
      max_line_length: 120

```
If I run `getx sort`, it will break paragraphs with more than 80 characters into multiple lines.

The `max_line_length: 120` that I configured is useless.

In VS Code, I configured this and it works well:
```json
"[dart]": {
  "editor.rulers": [120],
},
```
