### ISSUE TITLE
Can't install a local package 

### ISSUE THREAD

**Issue by BeliliFahem** [jonataslaw/get_cli#54]
Can't install a local package by providing the path to.

```
dependencies:
  flutter:
    sdk: flutter
  muqel_api: # <-- my local package
    path: ./api/muqel_api
  provider: ^4.3.3

```
