### ISSUE TITLE
Command run twice

### ISSUE THREAD

**Issue by liemfs** [jonataslaw/get_cli#65]
Simple command like **get help**, resulting **list available commands** twice

```
List available commands:

  create:
    controller:  Generate controller
    page:  Use to generate pages
    project:  Use to generate new project
    provider:  Create a new Provider
    screen:  Generate new screen
    view:  Generate view
  generate:
    locales:  Generate translation file from json files
    model:  generate Class model from json
  help:  Show this help
  init:  generate the chosen structure on an existing project:
  install:  Use to install a package in your project (dependencies):
  remove:  Use to remove a package in your project (dependencies):
  sort:  Sort imports and format dart files
  update:  To update GET_CLI
  -version:  Shows the current CLI version'



List available commands:

  create:
    controller:  Generate controller
    page:  Use to generate pages
    project:  Use to generate new project
    provider:  Create a new Provider
    screen:  Generate new screen
    view:  Generate view
  generate:
    locales:  Generate translation file from json files
    model:  generate Class model from json
  help:  Show this help
  init:  generate the chosen structure on an existing project:
  install:  Use to install a package in your project (dependencies):
  remove:  Use to remove a package in your project (dependencies):
  sort:  Sort imports and format dart files
  update:  To update GET_CLI
  -version:  Shows the current CLI version'
```
The same things happen if i execute **get create project**, **get create page**, it always run twice

This is what inside **get.bat**

```
@echo off
rem This file was created by pub v2.12.2.
rem Package: get_cli
rem Version: 1.4.5
rem Executable: get
rem Script: get
if exist "C:\Users\teguh\Documents\Flutter SDK\.pub-cache\global_packages\get_cli\bin\get.dart-2.12.2.snapshot" (
  dart "C:\Users\teguh\Documents\Flutter SDK\.pub-cache\global_packages\get_cli\bin\get.dart-2.12.2.snapshot" %*
  rem The VM exits with code 253 if the snapshot version is out-of-date.
  rem If it is, we need to delete it and run "pub global" manually.
  if not errorlevel 253 (
    goto error
  )
  pub global run get_cli:get %*
) else (
  pub global run get_cli:get %*
)
goto eof
:error
exit /b %errorlevel%
:eof


```
